================
Smart RSS Parser
===============

A Smart Wrapper for the Universal Feed Parser

Smart RSS Parser is a collection of fascades and helper code that wraps around
the Universal Feed Parser library. It helps to normalize data into common
objects regardless of the underlying RSS/atom format

The Universal Feed Parser can be found at:
http://code.google.com/p/feedparser


Documentation
-------------

Documentation can be autogenerated from the code we reccomend using
epydoc.

$ epydoc smartrssparser

Getting Help
------------

Adam Haney is the creator of Smart RSS Parser. He can be contacted at
adam.haney@retickr.com